# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!
configValidationMode: warn
service: dynamodbstream
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  lambdaHashingVersion: 20201221
  region: ap-south-1

# you can overwrite defaults here
#  stage: dev

# you can add statements to the Lambda function's IAM Role here
  iam:
    role:
      statement:
      - Effect: "Allow"
        Action:
          - dynamodb:GetRecords
          - dynamodb:GetShardIterator
          - dynamodb:DescribeStream
          - dynamodb:ListStreams
       

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  patterns:
#    - '!exclude-me.js'
#    - '!exclude-me-dir/**'
#    - include-me.js
#    - include-me-dir/**

functions:
  hello:
    handler: handler.hello
    events:
      - stream:
          type: dynamodb
          batchSize : 1
          startingPosition: LATEST
          batchWindow: 1
          arn: 
           Fn::GetAtt: 
                - StreamTable
                - StreamArn

# you can add CloudFormation resource templates here
resources:
 Resources:
   StreamTable:
     Type: AWS::DynamoDB::Table
     Properties:
      TableName: StreamTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
         - AttributeName: id
           KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

